image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_TOKEN $CI_REGISTRY
    - docker build -t $SERVER_IMAGE -f docker/http.server.dockerfile .
    - docker push $SERVER_IMAGE
    - docker build -t $WORKER_IMAGE -f docker/http.worker.dockerfile .
    - docker push $WORKER_IMAGE

  only:
    - master
    - dev

deploy:
  stage: deploy
  before_script:
    - if [ "$CI_COMMIT_REF_NAME" == "master" ]; then 
      export OPENSHIFT_PROJECT=$PRODUCTION_NAME;
      export PLUGIN_ROUTE=$PRODUCTION_ROUTE; 
    else
      export OPENSHIFT_PROJECT=$DEV_NAME;
      export PLUGIN_ROUTE=$DEV_ROUTE;
    fi

  script:
    - oc login $OPENSHIFT_SERVER --token=$OPENSHIFT_TOKEN
    - oc project $OPENSHIFT_PROJECT
    - oc process -f openshift-template.yml -p PLUGIN_NAME=$OPENSHIFT_PROJECT -p PLUGIN_ROUTE=$PLUGIN_ROUTE -p WORKER_IMAGE=$WORKER_IMAGE -p SERVER_IMAGE=$SERVER_IMAGE | oc apply -f -

  only:
    - master
    - dev