version: '3'

services:
  redis:
    image: redis:6-alpine
  web:
    depends_on:
      - redis
    image: neurogenpy-server:local-dev
    build:
      context: .
      dockerfile: ./http.server.dockerfile
    environment:
      NEUROGENPY_CELERY_BROKER: redis://redis:6379
      NEUROGENPY_CELERY_RESULT: redis://redis:6379
    ports:
      - "6001:6001"
  worker:
    depends_on:
      - redis
    image: neurogenpy-worker:local-dev
    build:
      context: .
      dockerfile: ./http.worker.dockerfile
    environment:
      NEUROGENPY_CELERY_BROKER: redis://redis:6379
      NEUROGENPY_CELERY_RESULT: redis://redis:6379