name: Mirror to EBRAINS gitlab

env:
  SOURCE_REPO: "AlaiaB/neurogenpy_plugin"
  DESTINATION_REPO: "https://github_push:${{ secrets.EBRAINS_GITLAB_ACCESS_TOKEN }}@gitlab.ebrains.eu/nikolas/neurogenpy_plugin"

on:
    push:
        branches: [ master, dev ]

jobs:
    to_ebrains:
        runs-on: ubuntu-latest
        steps:
            # This step will sync the master branch of the source repo (GitHub) with the master branch of the destination repo (GitLab)
            - name: syncmaster
              uses: wei/git-sync@v3
              with:
                source_repo: ${{ env.SOURCE_REPO }}
                source_branch: ${{ github.ref }}
                destination_repo: ${{ env.DESTINATION_REPO }}
                destination_branch: ${{ github.ref }}
            # This step will sync all tags from the source repo with the destination repo
            - name: synctags
              uses: wei/git-sync@v3
              with:
                source_repo: ${{ env.SOURCE_REPO }}
                source_branch: "refs/tags/*"
                destination_repo: ${{ env.DESTINATION_REPO }}
                destination_branch: "refs/tags/*"
